# Generated by Django 3.2.21 on 2023-09-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stamp',
            fields=[
                ('event_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('event_info', models.TextField()),
                ('event_start', models.DateField()),
                ('event_end', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='stamp_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_collected', models.BooleanField(default=False)),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Glover_main.stamp')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('stamps', models.ManyToManyField(related_name='collectors', through='Glover_main.stamp_collection', to='Glover_main.stamp')),
            ],
        ),
        migrations.AddField(
            model_name='stamp_collection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Glover_main.student'),
        ),
    ]
